const Areas = {
  erie: "Erie",
  wesleyville: "Wesleyville",
  wattsburg: "Wattsburg",
  wayne: "Wayne",
  waterford: "Waterford",
  washington: "Washington",
  venango: "Venango",
  unioncity: "Union City",
  summit: "Summit",
  springfield: "Springfield",
  platea: "Platea",
  northeast: "North East",
  millvillage: "Mill Village",
  millcreek: "Millcreek",
  mckean: "McKean",
  lebouef: "Fort Lebouef",
  lawrencepark: "Lawrence Park",
  lakecity: "Lake City",
  harborcreek: "Harborcreek",
  greenfield: "Greenfield",
  greene: "Greene",
  girard: "Girard",
  franklin: "Franklin",
  elkcreek: "Elkcreek",
  elgin: "Elgin",
  edinboro: "Edinboro",
  corry: "Corry",
  conneaut: "Conneaut",
  concord: "Concord",
  amity: "Amity",
  albion: "Albion",
};

export default Areas;
